<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SQELabs" name="BillRunFirst.Single_Customer_Rollback_Rebill" tests="6" failures="0" timestamp="10 May 2019 12:40:50 GMT" time="311.249" errors="1">
  <testcase name="EnterMultiCustomers_services_meterReads" time="79.620" classname="BillRunFirst.Single_Customer_Rollback_Rebill"/>
  <testcase name="EnterMultiCustomers_services_meterReads" time="68.557" classname="BillRunFirst.Single_Customer_Rollback_Rebill"/>
  <testcase name="BillRun_Cycle_For_Multiple_Customers" time="23.211" classname="BillRunFirst.Single_Customer_Rollback_Rebill"/>
  <testcase name="Bill_Run_with_MultipleCustomer" time="36.134" classname="BillRunFirst.Single_Customer_Rollback_Rebill"/>
  <testcase name="Single_Customer_Rollback" time="43.692" classname="BillRunFirst.Single_Customer_Rollback_Rebill"/>
  <testcase name="Single_Customer_rebill" time="60.035" classname="BillRunFirst.Single_Customer_Rollback_Rebill">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat BillRunFirst.Single_Customer_Rollback_Rebill.Single_Customer_rebill(Single_Customer_Rollback_Rebill.java:328)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- Single_Customer_rebill -->
</testsuite> <!-- BillRunFirst.Single_Customer_Rollback_Rebill -->
